### ISSUE TITLE
Prompt for action when invoked without arguments

### ISSUE THREAD

**Issue by ta2edchimp** [jfmengels/all-contributors-cli#10]
Considering the latest changes of `v2.0.0-beta7`, where the user is given a prompt when invoking `all-contributors add` without further arguments, I think it would be nice, when there's also a prompt when omitting any arguments at all.

I think of something like that:

```
$ all-contributors
```

- When there's no `.all-contributorsrc` file present:
  - ask whether to run the initialization step,
  - exit.

- When there's an `.all-contributorsrc` file present:
  - ask whether to `add` a new contributor (same as when invoking `all-contributors add`) ...
  - ask whether to only run `generate`,
  - exit.

Does that make sense?

**Comment by jfmengels** [comment]
Sure, can't hurt in making the cli more user-friendly. :+1:

**Comment by jfmengels** [comment]
@ta2edchimp I changed what you proposed when no rc file is found to directly launch the init command.

**Comment by ta2edchimp** [comment]
Cool, will try soon!

**Comment by jfmengels** [comment]
@kentcdodds @ta2edchimp Just published beta9. This also includes changing the JSON formatting in the rc that @kentcdodds really didn't like (can't blame him really).
@sarbbottam There's now a commit flag in the rc file, that if set to true, will auto-commit when using `add` (hopefully this will convince you guys use the `add` command :D).

(Yup, hijacking this issue to announce the release, but doing that in the commits makes it too hard to find again ^^')
