### ISSUE TITLE
Error: Cannot find module 'all-contributors-cli/cli'

### ISSUE THREAD

**Issue by xuchaoying** [jfmengels/all-contributors-cli#105]
- `all-contributors-cli` version: latest
- `node` version: v10.6.0
- `npm` (or `yarn`) version: npm v6.2.0

What you did:

I was trying to commit some code related to PR (#95), and the precommit script reported an error.  Then I tried `npm run add-contributor`, got same error. Any clue?

What happened:

![image](https://user-images.githubusercontent.com/8073251/43434937-5cdc7d38-94b0-11e8-895f-addbec0512f6.png)

**Comment by chinesedfan** [comment]
It's due to `kcd-scripts` is out-of-date. Check https://github.com/kentcdodds/kcd-scripts/releases/tag/v0.30.0.

**Comment by xuchaoying** [comment]
it works now, thx @chinesedfan
