### ISSUE TITLE
How to provide custom `types`?

### ISSUE THREAD

**Issue by chris-dura** [jfmengels/all-contributors-cli#106]
- `all-contributors-cli` version: v5.3.0
- `node` version: v8.11.3
- `npm` (or `yarn`) version: 6.2.0

Relevant code or config

```javascript
{
  "projectName": "my-cool-project",
  "projectOwner": "me",
  "repoType": "gitlab",
  "repoHost": "https://gitlab.my-company.com",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": false,
  "types": {
    custom: {
      symbol: '📝',
      description: 'Some custom type',
    }
  }
  "contributors": [
    {
      "login": "dura",
      "name": "Christopher Dura",
      "avatar_url": "https://gitlab.my-company.com/uploads/-/system/user/avatar/114/avatar.png",
      "profile": "https://gitlab.my-company.com/dura",
      "contributions": [
        "code",
        "custom"
      ]
    }
  ]
}
```

What you did:

Tried to add a custom contribution type.

What happened:

Nothing.

Reproduction repository:

Problem description:

I would like to use my own custom `types` of contributions, and the docs indicate that I should be able to use the [`types` config](https://github.com/jfmengels/all-contributors-cli#configuration) to do that. However, it is unclear, and I could really use an example configuration showing how to do that...

Suggested solution:

Someone give me a snippet of config I would need, or maybe update the README with an example config showing how to use all the options.

**Comment by chinesedfan** [comment]
Hi @chris-dura, because your `..all-contributorsrc` is not a valid JSON, which includes a lot of errors. And of course, this tool didn't give right tips.

```
 "types": {
    custom: { // not wrapped by double quotes
      symbol: '📝',
      description: 'Some custom type', // wrapped by single quotes
    }
  } // missing comma
```

**Comment by chris-dura** [comment]
Thanks, my IDE wasn't recognizing `.all-contributorsrc` as a JSON file, so I didn't get any lint errors... 😖 

```json
{
  "projectName": "my-cool-project",
  "projectOwner": "me",
  "repoType": "gitlab",
  "repoHost": "https://gitlab.my-company.com",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": false,
  "types": {
    "custom": {
      "symbol": "📝",
      "description": "Some custom type",
    }
  },
  "contributors": [
    {
      "login": "dura",
      "name": "Christopher Dura",
      "avatar_url": "https://gitlab.my-company.com/uploads/-/system/user/avatar/114/avatar.png",
      "profile": "https://gitlab.my-company.com/dura",
      "contributions": [
        "code",
        "custom"
      ]
    }
  ]
}
```
