### ISSUE TITLE
Format like regular JSON

### ISSUE THREAD

**Issue by kentcdodds** [jfmengels/all-contributors-cli#11]
Maybe this is just a personal style thing, but I'd reeeeally like to _at least_ configure this to not reformat my json file with comma-first style.

Happy to make a PR if you could give me some direction.

**Comment by jfmengels** [comment]
Would love having PRs incoming, but this was a pretty easy fix. I want to add a few things to the project and I'll make a release soon-ish (maybe as soon as tonight).

**Comment by kentcdodds** [comment]
Thanks!

**Comment by jfmengels** [comment]
Shouldn't you get back to interviewing? I'm watching you :p

**Comment by kentcdodds** [comment]
:sweat_smile:

**Comment by jfmengels** [comment]
Haa!, saw the smile live :D
