### ISSUE TITLE
Emoji links are not accessible on GitLab

### ISSUE THREAD

**Issue by chris-dura** [jfmengels/all-contributors-cli#119]
- `all-contributors-cli` version: `5.4.1`
- `node` version: `v8.12.0`
- `npm` (or `yarn`) version: `6.4.1`

Relevant code or config

**GitLab**
```md
[💻](https://gitlab.com/foo/commits "Code")
```
```html
<a href="https://gitlab.com/foo/commits" title="Code">
   <gl-emoji title="personal computer" data-name="computer" data-unicode-version="6.0">💻</gl-emoji>
</a>
```
**GitHub**
```md
[💻](https://github.com/foo/commits "Code")
```
```html
<a href="https://github.com/foo/commits" title="Code"> 
  <g-emoji class="g-emoji" alias="computer" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f4bb.png">💻</g-emoji>
</a>
```

What you did:

Navigated my README.md on GitLab using VoiceOver on Mac.

What happened:

When focused on the emoji links, the SR announces the links with the title of the emoji, instead of the actual contribution type, which is largely unhelpful for someone using AT.

Reproduction repository:

https://gitlab.com/snippets/1785217

Problem description:

So, after further investigation, it looks like this issue is probably with GitLab itself. In particular, their `<gl-emoji>` component is using a `title` attribute which overrides the `<a>` tag's `title`. GitHub's `<g-emoji>` component does not do this.

I've filed an issue on GitLab for reference: https://gitlab.com/gitlab-org/gitlab-ee/issues/8622

Suggested solution:

I suppose the ideal solution is for GitLab to fix their `<gl-emoji>` component.

**Comment by kentcdodds** [comment]
Yeah, it looks like there's not much we can do. Sorry about that ☹️

Hopefully gitlab can fix it!
