### ISSUE TITLE
Add reference to the spec

### ISSUE THREAD

**Issue by kentcdodds** [jfmengels/all-contributors-cli#12]
As noted in the spec, you need to have a reference to the emoji key and the spec itself:

```
Thanks goes to these wonderful people ([emoji key](https://github.com/kentcdodds/all-contributors#emoji-key)):

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
table stuff
<!-- ALL-CONTRIBUTORS-LIST:END -->

This project follows the [all-contributors](https://github.com/kentcdodds/all-contributors) specification.
Contributions of any kind welcome!
```

Happy to make a PR with some direction

**Comment by jfmengels** [comment]
I don't see what is missing https://github.com/jfmengels/all-contributors-cli#contributors :confused:

Would love a PR fixing it (whatever might be broken?). What kind of directions do you need? I don't have a contributing file sorry, will try to work on one.

**Comment by kentcdodds** [comment]
Sorry, should have been more clear. I would prefer that everything is generated, not just the section heading and the table. Right now, (unless I'm mistaken), when you generate for the first time, it only adds:

```
## Contributors

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
table stuff
<!-- ALL-CONTRIBUTORS-LIST:END -->
```

But I would prefer it to add:

```
## Contributors

Thanks goes to these wonderful people ([emoji key](https://github.com/kentcdodds/all-contributors#emoji-key)):

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
table stuff
<!-- ALL-CONTRIBUTORS-LIST:END -->

This project follows the [all-contributors](https://github.com/kentcdodds/all-contributors) specification.
Contributions of any kind welcome!
```

Thanks!

**Comment by jfmengels** [comment]
Aaahh... yes of course, that makes sense. Would be great :+1:

Well, if you don't mind spending time working on it, here are some directions:
- The contributor list/section gets generated here https://github.com/jfmengels/all-contributors-cli/blob/master/lib%2Finit%2FinitContent.js#L27
- Tests for it are here: https://github.com/jfmengels/all-contributors-cli/blob/master/lib%2Finit%2FaddContributorsList.test.js (AVA :rocket:)
- To test it manually, use `./cli.js init`.
- Currently, we check whether there is a contributors section. If yes, we add a list, if not, we create a section. If you wish to, I don't mind if you simply add a section and let the user handle the merge of his old and the generated section.
- Note: I use lodash/fp (and I made some docs for it [here](https://gist.github.com/jfmengels/6b973b69c491375117dc), hope it won't confuse you.

Thanks in advance, let me know if I can be of more help :)

**Comment by kentcdodds** [comment]
Hey @jfmengels, this looks like a great [`first-timers-only`](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue. Would you be interested in creating a label and setting this up as a first timer's issue? Here's a good example of one: https://github.com/kentcdodds/webpack-validator/issues/35

**Comment by jfmengels** [comment]
Sure, sounds good.

**Comment by jccguimaraes** [comment]
is there any one picking this up?

**Comment by jfmengels** [comment]
No one picked it up yet. Would you like to? :)

**Comment by jccguimaraes** [comment]
haven't looked at the code, but i can give a spin 👍

**Comment by jfmengels** [comment]
Cool, that'd be great! :smile: 

Let me know if you need help with anything :)

**Comment by jccguimaraes** [comment]
hey, are you in gitter? i can't seem to run 3rd point

**Comment by jfmengels** [comment]
Fixed thanks to @jccguimaraes :)
