### ISSUE TITLE
GitHub API rate limit exceeded for xxx

### ISSUE THREAD

**Issue by jakebolam** [jfmengels/all-contributors-cli#121]
- `all-contributors-cli` version: 5.4.1
- `node` version: v8.11.3
- `npm` (or `yarn`) version: yarn: 1.7.0

Relevant code or config:
n/a

What you did:
Ran `yarn all-contributors check`

What happened:
Crashed:
<img width="731" alt="screen shot 2018-12-23 at 10 48 42 am" src="https://user-images.githubusercontent.com/3534236/50380369-5ad5b600-06a0-11e9-8fa9-2161dcd4775c.png">

Reproduction repository:
Run commands which call the github API for 50+ times in more than an hour (note this is not limited to all-contributors/or your comupter, other programs on your machine and network contribute to this 50 limit for unauthenticated requests:
https://developer.github.com/v3/rate_limit/

Problem description:
API limit hit for all contributors

```
yarn all-contributors check
yarn run v1.7.0
$ /code/codewatch/node_modules/.bin/all-contributors check
API rate limit exceeded for xxx.xx.xx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Suggested solution:
A way to provide a GITHUB_AUTH_TOKEN env var which is attached to github requests to avoid api limits.

**Comment by jakebolam** [comment]
I put together an example of the changes required: https://github.com/jfmengels/all-contributors-cli/pull/122

**Comment by jakebolam** [comment]
FYI This is cropping up on a number of projects. It also appears to be affecting all-contributors-cli, when a contributor was trying to add himself here: https://github.com/jfmengels/all-contributors-cli/pull/97

**Comment by klieret** [comment]
I still run into this with the latest version of the cli, so I do not believe this has been fully fixed.
