### ISSUE TITLE
Publish 2.0.0... again?

### ISSUE THREAD

**Issue by kentcdodds** [jfmengels/all-contributors-cli#13]
You have some beta versions that were released more recently than the `2.0.0` which makes things pretty confusing. Could you publish a 2.0.1 or something? Maybe even a `3.0.0` if there are breaking changes?

**Comment by jfmengels** [comment]
Yeah sure. Sorry about not doing this sooner. I released the beta11 version I was pretty content with, and then got no feedback (meaning people were probably pretty happy with it, or just stopped using it). At that point, I should have siply released the non-beta version.
(Man it feels like ages ago, but it was only a month ago oO)

There were some breaking changes between the various 2.0 versions, so just to be on the safe side, I'm publishing it as v3.

**Comment by kentcdodds** [comment]
Awesome. I'm going to start using it in all of my projects because it just works great. I've added it to [my (wip) generator](https://github.com/kentcdodds/generator-kcd-oss) :-)

**Comment by jfmengels** [comment]
Cool! Very glad to hear that!

`v3.0.0` is out now :)
