### ISSUE TITLE
Force image size?

### ISSUE THREAD

**Issue by kentcdodds** [jfmengels/all-contributors-cli#14]
For some reason, GitHub doesn't size avatars which haven't yet been set like [here](https://github.com/kentcdodds/p-s/tree/c75cba64100d462a977e4bff341e9cf2ddc89151#contributors)

<img width="746" alt="screen shot 2016-05-02 at 9 59 15 am" src="https://cloud.githubusercontent.com/assets/1500684/14966629/b0ebc9c2-1070-11e6-88bc-6688b29c4432.png">

Is there a way we could format the table to force an image size?

**Comment by jfmengels** [comment]
I don't see the problem, this put emphasis on beginners, wasn't that really important to you?

More seriously, you're right, it doesn't work well with those images. It looks like we can fix the size with `<img src="https://avatars.githubusercontent.com/u/802242?v=3&s=100" alt="Drawing" style="width: 100px;"/>`. WIll play with it a bit and see what the drawbacks will be.

**Comment by jfmengels** [comment]
setting a style property doesn't work in GH (but works in Atom), but setting a width property directly works
`<img src="https://avatars.githubusercontent.com/u/802242?v=3" width="100px;"/>`

I've added your section at the top here https://github.com/jfmengels/all-contributors-cli/blob/t/README.md. Do you mind proofing this before and changing it in the tool? I've removed what I think was the markdown alt text (?) of the username.

**Comment by kentcdodds** [comment]
That's perfect :+1: Thanks@!

**Comment by jfmengels** [comment]
Fixed and released in `v3.0.1`. I accidentally published with Node v6, which has a `npm` version with problems (some files are not published). This time it seems to work fine though. Let me know if it doesn't work for you, and I'll re-publish it.

**Comment by kentcdodds** [comment]
Cool! I'll give it a look soon. I've had that issue too. Crazy stuff. Thanks for working on this!

**Comment by kentcdodds** [comment]
Just tested this out and it works great. Thanks!

**Comment by jfmengels** [comment]
Yay! 🎉
