### ISSUE TITLE
Improvement: Filter contributors by branch

### ISSUE THREAD

**Issue by cezaraugusto** [jfmengels/all-contributors-cli#19]
Any possibility for this being included?

**Comment by kentcdodds** [comment]
Could you describe what you mean more fully?

**Comment by cezaraugusto** [comment]
Hi Kent, sure. Let me try to explain it better:

I have a forked repo, and would like to include only people who have contributed to the forked version. This way excluding people who have already contributed to the original source.

The point is that I'm making a translated version of a book (which I've set to another branch), and would like to include people that is helping me with the translation, but by including all contributors I would also include people that helped the original version, but not the translatable one.

**Comment by kentcdodds** [comment]
Hmmm... Well, IIUC, all-contributors-cli doesn't actually care about branches or source control at all. So you'd just have a different `.all-contributorsrc` file per branch. Maybe I'm missing something.

**Comment by cezaraugusto** [comment]
Sorry Kent, just read the source code to see how it works. Works as you expected. Thanks.
