### ISSUE TITLE
Add comment to the output so people know it's generated

### ISSUE THREAD

**Issue by kentcdodds** [jfmengels/all-contributors-cli#2]
In markdown, you can add a comment like so:

```
<!-- this is a comment in markdown and not rendered -->
```

It'd be great to add a comment above the output indicating that it's generated and people should not try to modify it directly. Probably direct them to where they can update the contributors (presumably in the rc file if #1 gets supported).

**Comment by jfmengels** [comment]
I like this, because it has another nice property: it can be used as an anchor. Right now, I feel that the system to parse the .md (or simply, the search for the contributors list) is kind of a hack. Having a tag serve as an anchor would make that simpler. I will probably add a "closing" tag too.

**Comment by jfmengels** [comment]
I think this should be man-made to start with, and should be generated with the `init` command described in #3.
