### ISSUE TITLE
Add an `init` command to generate rc files and a contributors section

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/all-contributors-cli#3]
In addition to the `add` command, it would be nice to have an `init` command that:
- requests the user for necessary configuration information (repo name, repo owner, contributor file path)
- Create an `rc` file
- Add a `## Contribution` section at the end of the contributor file if not available
- Add enclosing contributors list tags
- Add enclosing contributors list tags

**Comment by kentcdodds** [comment]
:+1:

**Comment by jfmengels** [comment]
Landed in 6c90a4567f8e94e7d9245b7db02656b3b4a8b656
