### ISSUE TITLE
generate chokes with `Cannot read property 'symbol' of undefined` 

### ISSUE THREAD

**Issue by jerodsanto** [jfmengels/all-contributors-cli#40]
Howdy!

First off, 💚 this! Thanks so much for building it 🙏 

We had Kent on [The Changelog](https://changelog.com/podcast/246) last week and he's convinced us to use all-contributors for our repo. I am generating now and a specific user account breaks the `generate` command. It is:

https://github.com/soleo

I cannot figure out what is different about Xinjiang's profile, but when I remove him from the list the command succeeds. When I put him back in it prints `Cannot read property 'symbol' of undefined` and exits early. Here is the exact JSON object in the file:

```json
{
      "login": "soleo",
      "name": "Xinjiang Shao",
      "avatar_url": "https://avatars3.githubusercontent.com/u/635858?v=3",
      "profile": "https://www.xinjiangshao.com",
      "contributions": [
        "docs",
        "code"
      ]
}
```

Any ideas what's going on? Happy to help troubleshoot or submit a patch :smile:

**Comment by kentcdodds** [comment]
Interesting! Can you give a stack trace?

**Comment by jerodsanto** [comment]
Hmm how do I do that? I don't see a verbose mode in the usage...

**Comment by kentcdodds** [comment]
Oh really? Huh... I'm not sure. Let me try this out later.

**Comment by kentcdodds** [comment]
I was unable to reproduce. Could you give us your versions of node or npm? It could be that this package only supports Node v4 or greater.

**Comment by jerodsanto** [comment]
Lame. These kind of bugs are the worst, sorry 🤢 

Node 7.7.3
npm 4.1.2

Here's the entire .all-contributorsrc that works:

<details>
{
  "projectName": "changelog.com",
  "projectOwner": "thechangelog",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": false,
  "contributors": [
    {
      "login": "jerodsanto",
      "name": "Jerod Santo",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8212?v=3",
      "profile": "https://jerodsanto.net",
      "contributions": [
        "code",
        "doc",
        "infra"
      ]
    },
    {
      "login": "adamstac",
      "name": "Adam Stacoviak",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2933?v=3",
      "profile": "https://changelog.com/",
      "contributions": [
        "design",
        "code",
        "financial"
      ]
    },
    {
      "login": "codyjames",
      "name": "Cody Peterson",
      "avatar_url": "https://avatars0.githubusercontent.com/u/378665?v=3",
      "profile": "http://humanshapes.co",
      "contributions": [
        "design",
        "code"
      ]
    },
    {
      "login": "jakestutzman",
      "name": "Jake Stutzman",
      "avatar_url": "https://pbs.twimg.com/profile_images/562681393130377216/9Vyehvz8.jpeg",
      "profile": "http://elevate.co",
      "contributions": [
        "design"
      ]
    },
    {
      "login": "TuckerCowie",
      "name": "Tucker Cowie",
      "avatar_url": "https://avatars2.githubusercontent.com/u/7838530?v=3",
      "profile": "https://github.com/TuckerCowie",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "gerhard",
      "name": "Gerhard Lazu",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3342?v=3",
      "profile": "https://github.com/gerhard",
      "contributions": [
        "infra",
        "code"
      ]
    },
    {
      "login": "dennisreimann",
      "name": "Dennis Reimann",
      "avatar_url": "https://avatars1.githubusercontent.com/u/886?v=3",
      "profile": "https://dennisreimann.de",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "stve",
      "name": "Steve Agalloco",
      "avatar_url": "https://avatars0.githubusercontent.com/u/28044?v=3",
      "profile": "http://beforeitwasround.com",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "mcdado",
      "name": "David Gasperoni",
      "avatar_url": "https://avatars1.githubusercontent.com/u/898057?v=3",
      "profile": "http://david.gasperoni.org",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "nathany",
      "name": "Nathan Youngman",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4566?v=3",
      "profile": "https://nathany.com",
      "contributions": [
        "test"
      ]
    },
    {
      "login": "mavimo",
      "name": "Marco Vito Moscaritolo",
      "avatar_url": "https://avatars3.githubusercontent.com/u/43941?v=3",
      "profile": "http://mavimo.org",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "fallenpeace",
      "name": "0x4e",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5904417?v=3",
      "profile": "https://github.com/fallenpeace",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "sotojuan",
      "name": "Juan Soto",
      "avatar_url": "https://avatars1.githubusercontent.com/u/8217766?v=3",
      "profile": "https://juansoto.me",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "lucidstack",
      "name": "Andrea Rossi",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1248581?v=3",
      "profile": "https://github.com/lucidstack",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "Tuxified",
      "name": "Tonći Galić",
      "avatar_url": "https://avatars3.githubusercontent.com/u/51889?v=3",
      "profile": "http://tuxified.com",
      "contributions": [
        "infra"
      ]
    },
    {
      "login": "iamjarvo",
      "name": "Jearvon Dharrie",
      "avatar_url": "https://avatars2.githubusercontent.com/u/321306?v=3",
      "profile": "http://jearvondharrie.com",
      "contributions": [
        "code"
      ]
    }
  ]
}
</details>
<hr>
And here's the one that fails:

<details>
{
  "projectName": "changelog.com",
  "projectOwner": "thechangelog",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": false,
  "contributors": [
    {
      "login": "jerodsanto",
      "name": "Jerod Santo",
      "avatar_url": "https://avatars3.githubusercontent.com/u/8212?v=3",
      "profile": "https://jerodsanto.net",
      "contributions": [
        "code",
        "doc",
        "infra"
      ]
    },
    {
      "login": "adamstac",
      "name": "Adam Stacoviak",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2933?v=3",
      "profile": "https://changelog.com/",
      "contributions": [
        "design",
        "code",
        "financial"
      ]
    },
    {
      "login": "codyjames",
      "name": "Cody Peterson",
      "avatar_url": "https://avatars0.githubusercontent.com/u/378665?v=3",
      "profile": "http://humanshapes.co",
      "contributions": [
        "design",
        "code"
      ]
    },
    {
      "login": "jakestutzman",
      "name": "Jake Stutzman",
      "avatar_url": "https://pbs.twimg.com/profile_images/562681393130377216/9Vyehvz8.jpeg",
      "profile": "http://elevate.co",
      "contributions": [
        "design"
      ]
    },
    {
      "login": "TuckerCowie",
      "name": "Tucker Cowie",
      "avatar_url": "https://avatars2.githubusercontent.com/u/7838530?v=3",
      "profile": "https://github.com/TuckerCowie",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "gerhard",
      "name": "Gerhard Lazu",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3342?v=3",
      "profile": "https://github.com/gerhard",
      "contributions": [
        "infra",
        "code"
      ]
    },
    {
      "login": "dennisreimann",
      "name": "Dennis Reimann",
      "avatar_url": "https://avatars1.githubusercontent.com/u/886?v=3",
      "profile": "https://dennisreimann.de",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "soleo",
      "name": "Xinjiang Shao",
      "avatar_url": "https://avatars3.githubusercontent.com/u/635858?v=3",
      "profile": "https://www.xinjiangshao.com",
      "contributions": [
        "docs",
        "code"
      ]
    },
    {
      "login": "stve",
      "name": "Steve Agalloco",
      "avatar_url": "https://avatars0.githubusercontent.com/u/28044?v=3",
      "profile": "http://beforeitwasround.com",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "mcdado",
      "name": "David Gasperoni",
      "avatar_url": "https://avatars1.githubusercontent.com/u/898057?v=3",
      "profile": "http://david.gasperoni.org",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "nathany",
      "name": "Nathan Youngman",
      "avatar_url": "https://avatars2.githubusercontent.com/u/4566?v=3",
      "profile": "https://nathany.com",
      "contributions": [
        "test"
      ]
    },
    {
      "login": "mavimo",
      "name": "Marco Vito Moscaritolo",
      "avatar_url": "https://avatars3.githubusercontent.com/u/43941?v=3",
      "profile": "http://mavimo.org",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "fallenpeace",
      "name": "0x4e",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5904417?v=3",
      "profile": "https://github.com/fallenpeace",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "sotojuan",
      "name": "Juan Soto",
      "avatar_url": "https://avatars1.githubusercontent.com/u/8217766?v=3",
      "profile": "https://juansoto.me",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "lucidstack",
      "name": "Andrea Rossi",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1248581?v=3",
      "profile": "https://github.com/lucidstack",
      "contributions": [
        "code"
      ]
    },
    {
      "login": "Tuxified",
      "name": "Tonći Galić",
      "avatar_url": "https://avatars3.githubusercontent.com/u/51889?v=3",
      "profile": "http://tuxified.com",
      "contributions": [
        "infra"
      ]
    },
    {
      "login": "iamjarvo",
      "name": "Jearvon Dharrie",
      "avatar_url": "https://avatars2.githubusercontent.com/u/321306?v=3",
      "profile": "http://jearvondharrie.com",
      "contributions": [
        "code"
      ]
    }
  ]
}
</details>
<hr>

Hope that helps...

**Comment by kentcdodds** [comment]
Whelp, I can find three places where this error could be thrown. If you could dive into your `node_modules` and add console.log statements around these that would be very helpful: [1](https://github.com/jfmengels/all-contributors-cli/blob/1305a7cd92cfaf29aab0e1d46b6a9659c750b560/lib/contributors/prompt.js#L15), [2](https://github.com/jfmengels/all-contributors-cli/blob/bae31e1f477fc9fbc7bb2d5752ddbd28ac289dd5/lib/generate/format-contribution-type.js#L16), [3](https://github.com/jfmengels/all-contributors-cli/blob/bae31e1f477fc9fbc7bb2d5752ddbd28ac289dd5/lib/generate/format-contribution-type.js#L27)

**Comment by jerodsanto** [comment]
And the answer was.... Door #2! 🚪

The problem was for that one entry I had typed "docs" instead of "doc" so `getType` would return undefined for that entry, which leads to the dreaded `Cannot read property of 'symbol' for undefined` on line 16.

In the end: user error. 😔

I would suggest a check to see if a `type` is found and printing an error message if not, so the user at least knows they have a typo or plural form mucking things up.

Either way, feel free to close this issue. Thanks!

**Comment by kentcdodds** [comment]
Ah! Shucks! Yes, let's add a check and throw a more useful error. Would you like to [makeapullrequest.com](http://makeapullrequest.com)? :smile:

**Comment by jerodsanto** [comment]
Happy to. How do I run the tests?

**Comment by kentcdodds** [comment]
Sorry, this project should probably have a `CONTRIBUTING.md`... After installing the dependencies (`npm install`) run `npm test`.

**Comment by kentcdodds** [comment]
And thank you!

**Comment by jfmengels** [comment]
Thanks a lot @jerodsanto! (By the way, big fan of the show!)
