### ISSUE TITLE
generate is a noop

### ISSUE THREAD

**Issue by jmeas** [jfmengels/all-contributors-cli#46]
Hi there!

I'm trying to use this CLI for the first time, and it must be that I'm making a silly mistake. When I run `all-contributors generate`, nothing happens.

I ran the init script, then added a contributor:

```js
{
  "projectName": "resourceful-redux",
  "projectOwner": "jmeas",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": true,
  "contributors": [
    {
      "login": "jmeas",
      "name": "James, please",
      "avatar_url": "https://avatars3.githubusercontent.com/u/2322305?v=4",
      "profile": "http://www.jmeas.com",
      "contributions": [
        "code",
        "plugin",
        "doc"
      ]
    }
  ]
}
```

README.md exists. I also created CONTRIBUTORS.md for kicks. Neither of these files are updated when I run `generate`.

I'm sure I'm just missing something basic. I looked through #6 for ideas, but nothing seemed to stand out as a mistake that I was making. Any thoughts?

Thanks for reading!

**Comment by jmeas** [comment]
I dug into the code, and was able to fix it by manually adding:

```
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- ALL-CONTRIBUTORS-LIST:END -->
```

into the files that I want updated. I'm going to close this issue for now, but if this is a step that I should add to the README, let me know and I'll PR it.

Thanks!

**Comment by kentcdodds** [comment]
I'm pretty sure that the comment is added when you initialize things, but honestly I don't really know because [my generator](https://github.com/kentcdodds/generator-kcd-oss) has all that stuff baked in and ready to go 😅

**Comment by jmeas** [comment]
It's entirely possible that the init command errored, and I just didn't notice it :)
