### ISSUE TITLE
contributor cards in second row and onwards are not in bold

### ISSUE THREAD

**Issue by revelt** [jfmengels/all-contributors-cli#54]
Hi all,

Currently only the first row is in bold:

![bold-not-bold](https://user-images.githubusercontent.com/8344688/32311746-201d943e-bf92-11e7-8067-e55bedce2676.png)

If we added double asterisks on every card's label on second row and onwards, we could make all cards look the same - in bold:

```md
**[<img src="https://avatars3.githubusercontent.com/u/5038030?v=4" width="100px;"/><br /><sub>Charlike</sub>](https://github.com/tunnckocore)**<br />
```

What do you think? 

Btw I'm not going to contribute any code to this, feel free to grab it.

**Comment by machour** [comment]
Nice catch! This is due to the first row being rendered in a `<thead>`.

**Comment by kentcdodds** [comment]
Yes, I'd love this to be fixed. I don't particularly care how. Would anyone like to submit a pull request?

**Comment by machour** [comment]
I'll take care of it :)
