### ISSUE TITLE
Duplicate entries when adding a contributor twice

### ISSUE THREAD

**Issue by GantMan** [jfmengels/all-contributors-cli#62]
if I add the same user with the same contributions, shouldn't it just no op?

And then if I add an existing user with a new contribution, shouldn't it just modify that contributor's contributions array?  As far as for a CLI, it should be smart about the existing contents of the `.all-contributorsrc` correct?

**Comment by kentcdodds** [comment]
If I'm not mistaken, that's what it does. If it doesn't do that already, then that's a bug.

**Comment by GantMan** [comment]
Mark as bug
![idempotent](https://user-images.githubusercontent.com/997157/32563625-5e5efd8e-c477-11e7-9887-6bd2716e9c61.gif)

**Comment by machour** [comment]
@GantMan tried with 4.7.0, I can't reproduce what you're describing:

```shell

# no differences on start

🍺  ~/git-point (master)*$ git diff .all-contributorsrc
🍺  ~/git-point (master)*$ ./node_modules/.bin/all-contributors add foo doc

# foo correctly added

🍺  ~/git-point (master)*$ git diff .all-contributorsrc
diff --git a/.all-contributorsrc b/.all-contributorsrc
index 6e89eaa..5bb0bbd 100644
--- a/.all-contributorsrc
+++ b/.all-contributorsrc
@@ -628,6 +628,15 @@
       "contributions": [
         "translation"
       ]
+    },
+    {
+      "login": "foo",
+      "name": "Maciej Pacut",
+      "avatar_url": "https://avatars0.githubusercontent.com/u/33384?v=4",
+      "profile": "http://dblp2.uni-trier.de/pers/hd/p/Pacut:Maciej",
+      "contributions": [
+        "doc"
+      ]
     }
   ]
 }
🍺  ~/git-point (master)*$ ./node_modules/.bin/all-contributors add foo doc
🍺  ~/git-point (master)*$ ./node_modules/.bin/all-contributors add foo doc
🍺  ~/git-point (master)*$ ./node_modules/.bin/all-contributors add foo doc
🍺  ~/git-point (master)*$ ./node_modules/.bin/all-contributors add foo doc

# No duplication

🍺  ~/git-point (master)*$ git diff .all-contributorsrc
diff --git a/.all-contributorsrc b/.all-contributorsrc
index 6e89eaa..5bb0bbd 100644
--- a/.all-contributorsrc
+++ b/.all-contributorsrc
@@ -628,6 +628,15 @@
       "contributions": [
         "translation"
       ]
+    },
+    {
+      "login": "foo",
+      "name": "Maciej Pacut",
+      "avatar_url": "https://avatars0.githubusercontent.com/u/33384?v=4",
+      "profile": "http://dblp2.uni-trier.de/pers/hd/p/Pacut:Maciej",
+      "contributions": [
+        "doc"
+      ]
     }
   ]
 }
🍺  ~/git-point (master)*$ ./node_modules/.bin/all-contributors add foo doc,code

# doc kept, code added when specifying old and new contribution

🍺  ~/git-point (master)*$ git diff .all-contributorsrc
diff --git a/.all-contributorsrc b/.all-contributorsrc
index 6e89eaa..a5053b1 100644
--- a/.all-contributorsrc
+++ b/.all-contributorsrc
@@ -628,6 +628,16 @@
       "contributions": [
         "translation"
       ]
+    },
+    {
+      "login": "foo",
+      "name": "Maciej Pacut",
+      "avatar_url": "https://avatars0.githubusercontent.com/u/33384?v=4",
+      "profile": "http://dblp2.uni-trier.de/pers/hd/p/Pacut:Maciej",
+      "contributions": [
+        "doc",
+        "code"
+      ]
     }
   ]
 }

# doc & code kept, and bugs added when specifying only the new contribution

🍺  ~/git-point (master)*$ ./node_modules/.bin/all-contributors add foo bugs
🍺  ~/git-point (master)*$ git diff .all-contributorsrc
diff --git a/.all-contributorsrc b/.all-contributorsrc
index 6e89eaa..3d38887 100644
--- a/.all-contributorsrc
+++ b/.all-contributorsrc
@@ -628,6 +628,17 @@
       "contributions": [
         "translation"
       ]
+    },
+    {
+      "login": "foo",
+      "name": "Maciej Pacut",
+      "avatar_url": "https://avatars0.githubusercontent.com/u/33384?v=4",
+      "profile": "http://dblp2.uni-trier.de/pers/hd/p/Pacut:Maciej",
+      "contributions": [
+        "doc",
+        "code",
+        "bugs"
+      ]
     }
   ]
 }

```

Can you provide the same test as me, adding a new user?

**Comment by GantMan** [comment]
Yup!  Fortunately, the whole thing is open source.

I created a ticket to add `all-contributors-cli` here: https://github.com/infinitered/solidarity/issues/114

It was provided in a PR here: https://github.com/infinitered/solidarity/pull/119
Investigating his PR, I tested it out and found the issue.   All the code is available here:  https://github.com/mattathompson/solidarity/tree/all-contributors

**Comment by machour** [comment]
@GantMan the project you're pointing at is using version 4.5.3. There were some changes that may have fixed this problem since then. Could you try with the latest version? ([4.7.0](https://github.com/jfmengels/all-contributors-cli/releases/tag/v4.7.0) released an hour ago)

And thank you 😊 🎉

**Comment by GantMan** [comment]
@machour - my global is 4.7.0, I just checked.

I also, started a fresh branch on master and tried it out: ❌ 
![image](https://user-images.githubusercontent.com/997157/32565862-e5b5b598-c47c-11e7-9371-640389f02d4a.png)

**Comment by machour** [comment]
`which all-contributors` from `~/Documents/Projects/playground/solidarity/` please.
I think that you are using the local (outdated) package here.

**Comment by GantMan** [comment]
![image](https://user-images.githubusercontent.com/997157/32569484-dc69508a-c486-11e7-856e-c31cbefbd85d.png)


I also updated the package locally, and it was nope.  Does this work on your machine?  Are you using 4.7 from npm or a `npm link` version?   I'm stuck on how I can figure it out :(

**Comment by kentcdodds** [comment]
Hmmm... We don't recommend installing this globally. And sadly we don't currently support a `--version` flag 😅

**Comment by machour** [comment]
@GantMan I'm using 4.7.0 from npm on `gitpoint/git-point`, as well as `./cli.js` directly in this repository. Both work just fine.

As Kent mentioned, I think it would be better to get rid of your global package.

Then you may need to add some `console.log()` commands around here in your local package: 
   https://github.com/jfmengels/all-contributors-cli/blob/master/lib/contributors/add.js#L44
to understand what's going on.

Let us know what you find out 🕵️

**Comment by kentcdodds** [comment]
Are you sure that your global version of `all-contributors` is the latest version? I suggest you uninstall it globally and just use the local installation. `./node_modules/.bin/all-contributors` should do it, or you might use `npx`, `yarn`, or [this method](https://www.youtube.com/watch?v=2WZ5iS_3Jgs) to run binaries of locally install packages.

**Comment by GantMan** [comment]
Verified version 4.7
![image](https://user-images.githubusercontent.com/997157/32570753-be62d224-c48a-11e7-9dda-ccdfeee5760e.png)
Page 2
![image](https://user-images.githubusercontent.com/997157/32570778-ce4e5118-c48a-11e7-967d-fb53b67b9044.png)

Machine specs:
![image](https://user-images.githubusercontent.com/997157/32570811-f2637be6-c48a-11e7-9b00-6e1ce1e2909d.png)

**Comment by GantMan** [comment]
I broke the code open and found the bug.  PR coming soon hopefully.
