### ISSUE TITLE
Add emoji for Report

### ISSUE THREAD

**Issue by GantMan** [jfmengels/all-contributors-cli#68]
Some people add code coverage reports, cleanliness reports, and more.

Would be cool to have a report option.

**Comment by kentcdodds** [comment]
Interesting! Hmmm... I've found those kinds of reports to be via automated tools. Can you give me an example? That'll help us decide what emoji to use and whether it can be made more or less generic.

**Comment by GantMan** [comment]
Agreed it's automated.  Just like Tests are automated, but someone added those tests.   In my case, I have a contributor, who all he did was add code-coverage.   I'd like to give him an icon, but I don't know what fits best.

**Comment by kentcdodds** [comment]
Ah, gotcha, I would use 🚇 for `Infrastructure` 👍

**Comment by GantMan** [comment]
Good to know!  Thanks!
