### ISSUE TITLE
Wrong contribution type being added to .all-contributorsrc despite the error

### ISSUE THREAD

**Issue by machour** [jfmengels/all-contributors-cli#71]
If I add a contributor with a non existant contribution type (`bar`) an error message is printed 👍 but the contribution is still being added to the `.all-contributorsrc` file 👎 

```diff
🍺  ~/git-point (master)*$ yarn contributors:add foo bar
$ all-contributors add foo bar
Unknown contribution type bar for contributor foo
error Command failed with exit code 1.
🍺  ~/git-point (master)*$ git diff .all-contributorsrc
diff --git a/.all-contributorsrc b/.all-contributorsrc
index 3dc0ef3..fc4dee2 100644
--- a/.all-contributorsrc
+++ b/.all-contributorsrc
@@ -635,6 +635,15 @@
       "avatar_url": "https://avatars0.githubusercontent.com/u/3683673?v=4",
       "profile": "https://thecodetalker.github.io/",
       "contributions": []
+    },
+    {
+      "login": "foo",
+      "name": "Maciej Pacut",
+      "avatar_url": "https://avatars0.githubusercontent.com/u/33384?v=4",
+      "profile": "http://dblp2.uni-trier.de/pers/hd/p/Pacut:Maciej",
+      "contributions": [
+        "bar"
+      ]
     }
   ]
 }
```

What should happen is:
  * wrong contributions type being reported and not written in
  * if all contributions types were wrong, the user shouldn't be added in the file

**Comment by M-ZubairAhmed** [comment]
can i take this one?

**Comment by machour** [comment]
Of course :tada:
Let us know if you need any help!

**Comment by M-ZubairAhmed** [comment]
@machour sorry for keeping lagging on this for too long. 
So i tried to reproduce this error, when we add foo bar it does gets added to `.all-contributorsrc` but not to `README.md` when you try to generate. Is this correct?

**Comment by M-ZubairAhmed** [comment]
if user has input typo in one of the options as `add foo code,video,bar`. Should except bar others be added?
