### ISSUE TITLE
Incorrect message on add-contributors add

### ISSUE THREAD

**Issue by M-ZubairAhmed** [jfmengels/all-contributors-cli#76]
- `all-contributors-cli` version: 4.10.0
- `node` version:8.9.1
- `npm` (or `yarn`) version:1.3.2

Relevant code or config

```javascript
yarn add-contributor aravindballa review
```

What you did:
- tried adding new user with correct key and user name

What happened:
1. Added the info to .all-contributorsrc and readme
2. But shown wrong or misleading output
![image](https://user-images.githubusercontent.com/17708702/33585361-d6f8c2ee-d989-11e7-987d-7c22d7e8cc13.png)

Reproduction repository:

Problem description:
Incorrect output message

Suggested solution:
Should investigate why it happens and output a successfull message.

**Comment by kentcdodds** [comment]
Interesting. Thanks for reporting this. If you could do a little digging that would be really helpful. Thanks!

**Comment by M-ZubairAhmed** [comment]
sure. I am already on it

**Comment by evilsoft** [comment]
If you are still looking into this.
I ran into the same thing and found it happened :corn:sistantly when I had malformed json in the `all-contributorssrc`. O my project it happened after the readme was generated during a rebase. So the readme looked a-ok. did not notice until I went to add another fine person to the list.

Hope this helps!! 

node: 8.9.1
npm: 5.5.1
ac-cli: 4.11.0

**Comment by machour** [comment]
Thank you for the feedback @evilsoft, definitely worth catching Json errors and bailing out properly

**Comment by chinesedfan** [comment]
@M-ZubairAhmed I noticed that your console outputs `undefined`, which seems the same as #48. So maybe #102 has fixed it.

@evilsoft For invalid json, current codes have a try-catch arround the parsing logic.

**Comment by kentcdodds** [comment]
I'll go ahead and say this is resolved. Please file a new issue if it's not.
