### ISSUE TITLE
A few items

### ISSUE THREAD

**Issue by kentcdodds** [jfmengels/all-contributors-cli#8]
If you'd like, I can file individual issues for each of these individually based on what you're interested in actually implementing.

1. Rename properties? `login` -> `gitHubUsername`, `avatar_url` -> `avatarUrl`, -> `html_url` -> `htmlUrl`. Mostly just because I hate snake case. Feel free to reject this request :-)
2. I would love it if I didn't have to provide the `name`, `avatar_url`, and `html_url`. If we could use the public github API to get this information that'd be awesome. The `html_url` can default to the user's github page and they can override all of these if they want by giving something specific. But doing this means that if someone changes their name, we can get that update next time this is run. It also saves on typing :+1: 
3. It says the `imageSize` isn't required, but if I don't provide it, the size is set to `undefined`.
4. It'd be awesome if I didn't have to provide a project name/owner. You can find the github url with `git` and determine that information that way :-)
5. And another ping on #7 :-)

I just implemented this on [this new project](https://github.com/kentcdodds/eslint-find-new-rules) and overall it was an awesome experience. Thanks!

**Comment by jfmengels** [comment]
1. I don't mind, but I took them as that is what is returned by GitHub's user API. I don't mind renaming it though, but that adds some kind of translation from API response to the JSON to write.
Also, I'm not fond of having gitHubUsername, as all-contributors should not be IMO specific to GitHub. Currently the CLI only has support for GitHub API, but it doesn't have to be like that.

2. That's already the case, except if I'm misunderstanding your question. Use the add command `all-contributors add kentcdodds question`. Also, I was more thinking of only fetching the contributor info once, and if the contributor is already in the list, don't fetch their info the next time he gets updated. That way, if they for instance wants to have their name displayed differently than what is on GitHub and the change is done manually, it would not get overridden by querying GitHub.

3. Ah. Will take a look into it.

4. Sure, that would be nice. Would you happen to know a reliable `git` command to get that? I mean reliable in the sense that if I made a fork of a project, say kentcdodds/all-contributors to jfmengels/all-contributors, and I added a contributor, that it would not link to jfmengels/all-contributors but to kentcdodds/all-contributors.

Also, what is the part that you don't like: having to specify it manually, or having that info in the rc file? If the `init` subcommand added the correct info in the `rc`, would that be an ok solution?

5 Yep. Will get back on the horse and add this sometime soon ;)

Note: The latest release is a beta version, `npm i -g all-contributors-cli@beta`. Don't know if that solves some of the problem.

> I just implemented this on this new project and overall it was an awesome experience. Thanks!

Great to hear. And man... what timing. I'm introducing ESLint to several projects at work by making a shared config project. I feel like I'm going to use your tool pretty soon :D (hint: if it supports plugin rules, that would make it even greater)

**Comment by kentcdodds** [comment]
1. Ah! Didn't know that! :+1:
2. I actually am talking about what I have to put in the `.all-contributorsrc` file. I'd rather not have to include all those properties.
3. :+1:
4. Yeah, good point. Forks would make this really difficult... Maybe keep it the way it is. Yeah, for the `init` command (#3) we could have it pre-populate based on something like `git config --get remote.origin.url`.
5. Thanks!

> if it supports plugin rules, that would make it even greater

Definitely something I'm interested in adding :-)

**Comment by jfmengels** [comment]
2 - But that is taken care of by the `add` command. When you `add` a contributor, a request is made to the GH API and those fields are written in the `.all-contributorsrc` file. Except if you want to override stuff, you should not have to touch them, but never add them. Is it having that data in the file that is bothering you? Hit me on Gitter if I'm still misunderstanding stuff.

4 - Thanks for the command :)

**Comment by kentcdodds** [comment]
2 - Right, but I don't want to have to update that information in the future if someone changes their name for example, and if I'm not using the `add` command, I don't want to add it manually. I'd prefer the `generate` command to make the requests to the GitHub API for that data if it's not listed :+1:

**Comment by jfmengels** [comment]
Ah, so you'd like to define only the login and the eventual manually set fields, and let `generate` fetch the missing data without writing them into the `rc` file. Hmm... I made it this way so you would download the info once, and then be able to generate the contributors list fast and offline, which I think is the better way (or at least, better default way). I guess I could do that if there is missing information, why not... but I'm a bit worried about throttling in GH's API, not sure this is actually feasible when there are a few contributors.

Also, why would you not want to use `add`?

**Comment by kentcdodds** [comment]
> why would you not want to use `add`

I guess I mostly didn't think about it and I prefer to hand craft things when I get started. Maybe in the future I'll probably use it.

> I'm a bit worried about throttling in GH's API, not sure this is actually feasible when there are a few contributors.

Do you know what the limit is? If we could handle 50 contributors that'd be fine I'm sure. And if it becomes a problem we can address it then (add an auth token option or something).

I think the real dream for this thing would be to set up a bot that makes a PR to update the contributor's section anytime a change to the `rc` file is detected. That'd be sweeeeet.

**Comment by jfmengels** [comment]
For the limit, I thought it was 30 without token, and 50 with. Not sure it's the case though when I look at things like this: https://developer.github.com/v3/users/
> X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999

Will have to play with it a bit. If I see the limit is really high, I'll probably add it.

> the real dream for this thing would be to set up a bot that makes a PR to update the contributor's section

I was thinking of the same thing. I was thinking of creating a bot like eslint-bot or facebook's mention bot, that you would tell to do stuff inside an issue/PR:

```
Thanks @kentcdodds for your contribution

@all-contributors-bot add kentcdodds code
```
which would create a PR with the addition in the `rc` file and the updated contributor list. **That** would be sweet...

**Comment by kentcdodds** [comment]
![card-pokes-confirmation-joW44Re99ZfC8](https://camo.githubusercontent.com/211b73765185b387b9b5518b3dabda5de2bd2424/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f6a6f573434526539395a6643382f67697068792e676966)

That would be legit

**Comment by jfmengels** [comment]
@kentcdodds
- imageSize got fixed :)
- tags can be on the same line now!
- There is a init command!

Hope it makes you happy, let me know what you think :)
(Closing this thread, if you notice bugs --> new issue)

**Comment by jfmengels** [comment]
Hmm... now that I look at the README.md, having the comment tag on the same line breaks GH's markdown rendering (look fine in Atom though)... crap...

**Comment by kentcdodds** [comment]
Hmm, yeah, maybe for the badge instead of looking for the comment you just look for the generated badge?

**Comment by jfmengels** [comment]
Yeah, I guess that will have to do. Messy :(
Will work on it tonight
