### ISSUE TITLE
Support other sources other than Github

### ISSUE THREAD

**Issue by tigermarques** [jfmengels/all-contributors-cli#83]
- `all-contributors-cli` version: 4.10.1
- `node` version: 8.9.4
- `npm` (or `yarn`) version: npm 5.5.1

What you did:

I am generating the Contributors section, but my users exist in a local gitlab installation rather than github. 

Problem description:

I want to be able to add contributors using my gitlab local installation rather than github. Gitlab also has an api to retrieve user information, which contains the login, name, avatar url, and profile url. From what I was able to see, the only interaction wit github is in the `contributor/github.js`, and therefore it would be possible to extend this behavior to other providers (such as gitlab)

Suggested solution:

I can investigate as to how to implement such a solution if you see this as a desirable feature. It could be acieved either via a config file, the cli or in the package.json itself, so that the user would be able to change the default github option. One issue that may be important is that with my gitlab installation, I will need to provide a personal access token for these requests.

I will wait for your feedback prior to deep diving into implementation.

**Comment by machour** [comment]
Hey @tigermarques, this sounds like a cool feature indeed. An additional configuration option defaulting to `github` would be the way to go.

Feel free to open a PR for this feature!

**Comment by tigermarques** [comment]
Pull request #84 created for this. Still WIP.

**Comment by tigermarques** [comment]
Pull Request #84 ready for a first revision

**Comment by machour** [comment]
Wonderfully done mate! 👌

**Comment by kentcdodds** [comment]
Thanks! 👏
