### ISSUE TITLE
Self-hosted GitLab instance

### ISSUE THREAD

**Issue by chris-dura** [jfmengels/all-contributors-cli#89]
- `all-contributors-cli` version: `4.11.1`
- `node` version: `8.11.1`
- `npm` (or `yarn`) version: `5.8.0`

Relevant code or config

```javascript
// .all-contributorsrc
{
  "projectName": "hub",
  "projectOwner": "prototyping",
  "repoType": "gitlab",
  "repoHost": "https://gitlab.mycompany.com",
  "files": [
    "README.md"
  ],
  "imageSize": 100,
  "commit": false,
  "contributors": []
}

```

What you did:
I tried to add a contributor.
```shell
all-contributors add dura code
```

What happened:
I got this error:
```shell
Cannot read property 'username' of undefined
```

Reproduction repository:
n/a since we have a private self-hosted gitlab instance...

Problem description:

Changing the `repoType`, `repoHost` and `username` to my public GitHub accounts seems to work, so I suspect it has something to do with the self-hosted repo.
However, you mention changing `repoHost` to a self hosted repo in the [docs](https://github.com/jfmengels/all-contributors-cli#configuration)... so I'm assuming it is expected to work.

We do have 2FA enabled, could that be the problem?

Suggested solution:

Even with 2FA, we usually use the GitLab API by passing a [personal access token](https://docs.gitlab.com/ee/api/README.html#personal-access-tokens).

Perhaps providing an option to do that will suffice?

**Comment by machour** [comment]
Hi @chris-dura. As far as I remember, the GitLab connector was only tested with the public GitLab.com setup, and authentication is not handled yet.

This definitely needs some more work. Would you be available to work on a PR for that?

**Comment by chris-dura** [comment]
@machour I'll stick it in my wishlist and try to find some time, thanks for the response!

**Comment by xuchaoying** [comment]
same problem here
