### ISSUE TITLE
Getting "all-contributors: command not found" error

### ISSUE THREAD

**Issue by austintackaberry** [jfmengels/all-contributors-cli#92]
- `all-contributors-cli` version: 4.11.1
- `node` version: 8.11.2
- `npm` (or `yarn`) version: 6.0.1

What you did:

Followed the readme to install, init, and then generate.

What happened:

```
$ npm install --save-dev all-contributors-cli
$ npx all-contributors init
$ all-contributors generate
all-contributors: command not found
```

Suggested solution:

I don't know what I'm doing, but `$ npx all-contributors generate` seemed to do the trick for me.

I opened this issue because I didn't see this error in any of the other issues and perhaps others are running into this as well.

**Comment by austintackaberry** [comment]
Upon further review, it seems like `npx` allows you to use a cli tool that is installed locally, and you would need to install the tool globally if you wanted to omit the `npx` unless I am missing something. 

If that is the case, should the docs be changed to reflect this?

**Comment by kentcdodds** [comment]
I'm honestly not certain what you'd change about the docs for this, but sure, feel free to open a PR :)

**Comment by austintackaberry** [comment]
Anywhere where the docs suggest using the `all-contributors` command in the command line (multiple places in the Usage section), it should be prefaced with `npx`, or am I wrong?

**Comment by kentcdodds** [comment]
You might add a note that says:

> We recommend that you install `all-contributors-cli` as a dependency in your project. If you do that then you can run the `all-contributors` binary from within your `package.json` scripts, or you can run it in your terminal with `npx all-contributors`. Below we'll just show `all-contributors` to keep things simple.

I don't want to confuse people by including `npx` all over the place. Before we know it, everyone will include `npx` in their `package.json` scripts which is totally unnecessary. :)

**Comment by austintackaberry** [comment]
Yeah, that makes sense. Thanks for everything you do with this! It is awesome for making your project open and inviting.

**Comment by KirstieJane** [comment]
Hi - I found this thread really useful so I've put in a little pull request (#114) with the suggested text from @kentcdodds in https://github.com/jfmengels/all-contributors-cli/issues/92#issuecomment-391766876 above.

Totally fine to disregard or for any edits - @austintackaberry if you'd have put it in a different place just let me know!

**Comment by kentcdodds** [comment]
Thanks to @KirstieJane for the PR!
